#spring:
#  profiles: local
#    active: local

#local 환경
---
logging:
  level:
    root: warn
    com.rest.api: info
  path: /home/ec2-user/weedoctor_api/log
  file:
    max-history: 7

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weedoctor?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qufn12

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      generate-ddl: true
    show_sql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&amp;


